# Generated by Django 5.2.5 on 2025-10-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='device_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
