# Generated by Django 5.2.5 on 2025-10-13 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metabee_app', '0002_printer_device_id'),
    ]

    operations = [
    ]
