# Generated by Django 5.2.5 on 2025-10-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metabee_app', '0003_auto_20251012_2236'),
    ]

    operations = [
    ]
