# Generated by Django 5.2.5 on 2025-10-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metabee_app', '0004_auto_20251012_2237'),
    ]

    operations = [
    ]
