# Generated by Django 5.1.5 on 2025-10-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabee_app', '0005_auto_20251012_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
