# Generated by Django 5.1.5 on 2025-10-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabee_app', '0006_alter_printer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='device_id',
            field=models.CharField(default='xxxxxxxxxxxxxxxxxxxxxx', max_length=100),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(default='Default Printer', max_length=100),
        ),
    ]
