# Generated by Django 5.1.5 on 2025-11-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabee_app', '0007_alter_printer_device_id_alter_printer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='idle_range',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='printer',
            name='operating_range',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='printer',
            name='device_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
